Adapt to Cloudflare Workers environment
sidorares/node-mysql2 pull request #2289
Opened 2023-11-21 08:15 UTC by Mini256

try to close #2179

**Summary**

- To fix the error `window is not found`, replace node `Timers` with web timers
- To fix the error `Code generation from strings disallowed for this context`, using the static parser in PR #2099
- To fix the error `crypto.hash() is not a function`, polyfill node `crypto` with`webcrypto`, and modify the functions which directly/indirectly called the `crypto` library as async function.

**Works with Auth plugins**:

- [x] mysql_native_password
- [ ] caching_sha2_password
- [ ] sha256_password

**Usage**

For users, they need to:

1. Add `node_compat = true` flag to polyfill the missing node modules
2. Add `useStaticParser` flag to force mysql2 to use static parser.

For example: https://github.com/Mini256/mysql2-cloudflare-test/blob/1f339a85f4457b696f122503051991326dbc23dc/src/index.ts#L30

2023-11-21 11:33 UTC, shiyuhang0 commented on lib/connection.js
> +      this.stream = getStream(!!opts.config.ssl);
```suggestion
      this.stream = getStream(opts.config.ssl);
```

2023-12-25 07:38 UTC, shiyuhang0 commented
This PR can run on Cloudflare Workers with the following database:
- MySQL 5
- MySQL 8
- TiDB Serverless Cluster
- PlanetScale

@sidorares could you please approve to run the GitHub action?

2023-12-25 09:23 UTC, sidorares commented
@shiyuhang0 @Mini256 thanks for working on this! Could you document simple steps I can follow to try it myself?

2023-12-25 11:08 UTC, shiyuhang0 commented
> @shiyuhang0 @Mini256 thanks for working on this! Could you document simple steps I can follow to try it myself?

https://github.com/sidorares/node-mysql2/pull/2289/commits/3034a145abf9bf9cf18dad6e725fdbea7be8196e this commit add a step-by-step tutorial

2023-12-27 03:11 UTC, shiyuhang0 commented
CI is green. Maybe we can ignore the failure of CodeQL action, because the error is reported in the code that originally existed (just the location has changed)

2023-12-28 01:40 UTC, sidorares commented
> As for the static parser. We'd like to merge your PR #2099 rather than cherry-pick it into this PR. What's your opinion? @sidorares The static binary parser is also needed to make things work. `Code generation from strings disallowed for this context` still occurs when code goes through the binary parser.

I can probably merge it first, together with added binary protocol non-jit parser.
I don't like the flag name "useStaticParser", it reflects more implementation details rather than intention, but don't have better ideas. Can you think of a better flag name? "disableEvals" ? "strictMode" ( could be an umbrella flag, also prohibits cleartext plugin etc ). `disableGenFunction` ( again, too focused on implementation ). Naming things is hard 🤷‍♂️ 

re testing - thanks a lot for dev documentation. Are you aware of any way to test workers locally or in actions runtime? something similar to localstack. Ideally with the same checks, e.i errors when code tries to eval. Any container we can use for that?

2023-12-28 03:19 UTC, Mini256 commented
> Are you aware of any way to test workers locally or in actions runtime?

Cloudflare Workers provide an `unstable_dev` API for E2E / integration tests: https://developers.cloudflare.com/workers/wrangler/api/#unstable_dev

2023-12-28 03:51 UTC, shiyuhang0 commented
> I can probably merge it first, together with added binary protocol non-jit parser.
> I don't like the flag name "useStaticParser", it reflects more implementation details rather than intention, but don't have better ideas. Can you think of a better flag name? "disableEvals" ? "strictMode" ( could be an umbrella flag, also prohibits cleartext plugin etc ). `disableGenFunction` ( again, too focused on implementation ). Naming things is hard 🤷‍♂️

I prefer `disableEvals` among these names. You can also use other names, not good at naming for me :(

2023-12-28 05:08 UTC, sidorares commented
> I prefer `disableEvals` among these names. You can also use other names, not good at naming for me :(

I like it more than `useStaticParser`, I think I'll update in my branch ( together with a version for no evals binary parser ) and comment here when ready

2024-01-23 17:06 UTC, advancedtw commented
I have tested this pr on multiple MySQL server ranging from old 5.7 to more recent MySQL and MariaDB version locally and on deployed workers so far it works flawlessly. The only issue is having to set ```node_compat = true```  instead of ```compatibility_flags = [ "nodejs_compat" ]``` but that's a small price to pay. 
Also it's currently not possible to use drizzle with msyql driver but kysely works ok.

2024-01-24 13:54 UTC, elithrar commented
FYI:

* Other drivers (like `node-postgres` and `Postgres.js`) also require `node_compat = true` today
* We have plans to allow `nodejs_compat` to work: this will likely require us to better audit specific packages and conditionally load/exclude Node.js APIs that we don't have support for in Workers, or that don't make sense in a serverless environment like Workers.

Otherwise, we'd love to see this merged + we're bringing MySQL support to Hyperdrive: https://developers.cloudflare.com/hyperdrive/

2024-03-06 03:38 UTC, shiyuhang0 commented
I have resolved the conflict with master branch. 
@sidorares Hi, what's the process of no evals parser? I'd like to remove the related codes in the PR after that.

2024-03-06 03:46 UTC, wellwelwel commented
Hi, @shiyuhang0 🙋🏻‍♂️

If it's okay, I'd like to make a few simple suggestions in the documentation:

- Change from `.md` to `.mdx`
- Change the title from **Run on Cloudflare Workers** to **Cloudflare Workers**
- _I think it fits in the examples section, what do you think?_

2024-03-06 04:00 UTC, shiyuhang0 commented
> Hi, @shiyuhang0 🙋🏻‍♂️
> 
> If it's okay, I'd like to make a few simple suggestions in the documentation:
> 
> * Change from `.md` to `.mdx`
> * Change the title from **Run on Cloudflare Workers** to **Cloudflare Workers**
> * _I think it fits in the [**Examples**](https://sidorares.github.io/node-mysql2/docs/examples) section, what do you think?_

already doing this, will push a commit soon

2024-03-06 11:11 UTC, sidorares commented
@shiyuhang0 what do you think about `useStaticParser` flag name? Should we rename it to `disableEval` before its too late and somebody else depends on this name?

2024-03-07 05:46 UTC, shiyuhang0 commented
> @shiyuhang0 what do you think about `useStaticParser` flag name? Should we rename it to `disableEval` before its too late and somebody else depends on this name?

Both it is fine for me. But we shouldn't worry about modifying parameter names in an unmerged PR. For me, I think it can even be modified before release.

2024-03-27 03:12 UTC, m430 commented
I really need this feature. I need to use the node-mysql2 driver with Drizzle in Cloudflare Workers. If everything is confirmed to be correct, could you please merge this PR as soon as possible? Thanks

@sidorares

2024-03-27 08:11 UTC, advancedtw commented
@m430 last time I checked Drizzle/Mysql was not compatible with cloudflare even using this updated driver. That is because of some node compatibility issue.
If you really need a mysql driver for cf today! you can use a git dependecy or  @nora-soderlund [cloudflare-mysql](https://github.com/nora-soderlund/cloudflare-mysql/)

@shiyuhang0 disableEval makes more sense to me

2024-03-29 00:45 UTC, sidorares commented
@shiyuhang0 missed your message, I also prefer `disableEval`. Are you able to continue or you need someone to take over your work?

2024-05-06 02:22 UTC, shiyuhang0 commented
> @shiyuhang0 missed your message, I also prefer `disableEval`. Are you able to continue or you need someone to take over your work?

I push a new commit to use `disableEval` instead of `useStaticParser `. Is there anything else I need to do?

2024-05-06 21:09 UTC, elithrar commented
> Add node_compat = true flag to polyfill the missing node modules

Is there a path to instead supporting our modern `nodejs_compat` mode by updating imports (conditionally) vs using the legacy poly fill mode?

https://developers.cloudflare.com/workers/runtime-apis/nodejs/

2024-05-06 21:51 UTC, wellwelwel commented
> I have pushed a new commit to use `disableEval` instead of `useStaticParser `. Is there anything else I need to do?

_Just a note_, while in the docs it says `disableEval`, in all code it's `getStaticTextParser` 🙋🏻‍♂️

2024-05-07 08:39 UTC, shiyuhang0 commented
> > I have pushed a new commit to use `disableEval` instead of `useStaticParser `. Is there anything else I need to do?
> 
> _Just a note_, while in the docs it says `disableEval`, in code it's `useStaticParser` 🙋🏻‍♂️

I forget push the change in code

2024-11-24 17:43 UTC, focux commented
Does this PR works in his current state? Or do we have a list of the things that are missing to collaborate?

2024-12-15 21:37 UTC, wellwelwel commented
> Does this PR works in his current state? Or do we have a list of the things that are missing to collaborate?

Hi, everyone! I'd like to propose simplifying the process 🙋🏻‍♂️

Due to many responsibilities in a single _PR_, rebasing is necessary constantly, in addition to the difficulty of revising, I've tried to figure out the changes and the suggestion would be to create one refactoring at a time:

- ❇️ Adapt asynchronous methods _(probably no new tests will be needed, just make sure that all existing tests work, especially the new ones)_.
- ❇️ Create the `disableEval` option/feature _(any doubts and ideas about the name can be discussed in its dedicated PR)_.
  - New tests are essential.
- ❇️ Create the `secureStream` method.
  - I couldn't understand if this is a refactoring or a new feature, so if it's a new feature, tests are also important.
- ✅ Finally, include `pg-cloudflare` or `mysql2-cloudflare` optional dependencies, ensuring the download isn't done directly, plus the **Cloudflare Workers** documentation, closing the #2179.

---

By breaking down responsibilities, it's easier both to review and to prevent the constant need to rebase commits.
What do you think?

2024-12-16 01:31 UTC, Mini256 commented
> Create the disableEval option/feature

@wellwelwel Yes, we can discuss this in PR #2099 (or another dedicated PR) and use it as a precursor PR to support the new non-eval parser in mysql2, avoiding this PR from handling too many tasks. After that, we can rebase this PR.

2025-01-16 22:00 UTC, thomasgauvin commented
Hi folks! I'm on the Cloudflare Workers team. We've made some progress on our side to help this effort, in the process of adding more compat to workerd by adding support for node:net (https://github.com/cloudflare/workerd/pull/3315) and node:timers (https://github.com/cloudflare/workerd/pull/3346) which resolves some of the missing dependencies that have been noted in this thread. 

Eval is not something that we'll be able to land in workerd, so the non-eval parser would still be a missing piece

2025-02-04 20:44 UTC, wellwelwel commented
> Eval is not something that we'll be able to land in workerd, so the non-eval parser would still be a missing piece

Thanks for the notices, @thomasgauvin 🙋🏻‍♂️

In my previous comment, I mentioned breaking down the tasks into different _PRs_, but with your comment, I'm uncertain about what still needs to be done to make **MySQL2** compatible with **Cloudflare Workers**.

---

@Mini256 and @shiyuhang0, I have changed the title of the _PR_ to "`feat: support Cloudflare Workers`" and since #3365 was merged, both the binary and text static parsers will now be available, which allows us to move on to the next step (the option name used was in fact `disableEval`).

> [!NOTE]
> **npm** is not uploading the canary version, it's probably a momentary error.

2025-02-05 09:32 UTC, wellwelwel commented
The static parsers are already available in `3.12.1-canary.603c2463` 🎉

As mentioned by @sidorares in https://github.com/sidorares/node-mysql2/pull/3377#issuecomment-2636152104, I would like to draw your attention to this:

- https://x.com/CloudflareDev/status/1884699456018301020

Probably the documentation is the only remaining _piece_ now. @Mini256 and @shiyuhang0, after all your efforts, I would be happy if you'd like to finish this step to officially release it 🤝

2025-02-05 22:49 UTC, sidorares commented
node compatibility table: https://workers-nodejs-compat-matrix.pages.dev/

2025-02-08 20:27 UTC, i18nsite commented
> I did a simple test with `3.12.1-canary.603c2463` and connecting mysql in a non-SSL way can work properly. 👍
> 
> However, when I connect in SSL, I will get an error:
> 
> > [unenv] tls.createSecureContext is not implemented yet!
> 
> https://github.com/Mini256/mysql2-cloudflare-test/blob/main/src/index.ts
> 
> I will try to add this integration test to the node-mysql2 test and try to solve it.


still can't use in cloudflare worker

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/cfcron) failed.

  Uncaught Error: Dynamic require of "events" is not supported
    at null.<anonymous> (main.js:21:9)
    at null.<anonymous> (file:///Users/z/i18n/lib/state/cf/src/main.js:2989:50641)
    at null.<anonymous> (file:///Users/z/i18n/lib/state/cf/src/main.js:1:458)
    at null.<anonymous> (file:///Users/z/i18n/lib/state/cf/src/main.js:2989:53394)
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

2025-02-28 22:11 UTC, thomasgauvin commented
Hey folks! Are you using nodejs_compat flag? With the nodejs_compat flag in your wrangler.jsonc/wrangler.toml, and using the most recent version of the wrangler CLI, you should be able to use the static parser in a way that works on Cloudflare Workers

2025-02-28 22:35 UTC, thomasgauvin commented
I went ahead and created a repo that you can use as a reference for something that works @i18nsite @Mini256 @wellwelwel https://github.com/thomasgauvin/mysql2-on-cf-workers You'll have to excuse my quick code that does not make use of env variables for connection details but it does run on Cloudflare Workers now if you use one of the recent Wrangler releases. I'm using 3.111.0, and it's also supported on the 'deployed' Cloudflare Workers https://mysql2-on-cf-workers.toms-projects.workers.dev/

2025-02-28 22:49 UTC, wellwelwel commented
> Please let me know if there's anything else I can do to help!

@thomasgauvin, thanks for the update! I suppose all that's missing is just documenting `disableEval` option. Also, in order to check the condition mentioned by @i18nsite, I'll test your repository through an **SSL** connection.

Once this is confirmed, we can officially say that **MySQL2** supports **Cloudflare Workers** by release in fact the canary version 🚀

2025-03-01 15:43 UTC, thomasgauvin commented
@wellwelwel got it! Yes, I can confirm that `✘ [ERROR] Uncaught (in response) Error: [unenv] tls.createSecureContext is not implemented yet!` still occurs in the most recent workerd/wrangler releases, and we're working on this

2025-03-06 01:48 UTC, thomasgauvin commented
@wellwelwel update on this thread: creating tls context is not something that can be done from within the Cloudflare Workers runtime because it is the Cloudflare runners (which are responsible for running Workers isolates) that establish the outbound connections

What we're thinking here is to make it possible to set ssl certs in a [Hyperdrive](https://developers.cloudflare.com/hyperdrive/get-started/) configuration rather than in the code itself. [Bindings](https://developers.cloudflare.com/workers/runtime-apis/bindings/), such as the Hyperdrive binding or the [mTLS binding](https://developers.cloudflare.com/workers/runtime-apis/bindings/mtls/), is usually how we resolve these limitations. Then we'd recommend folks use mysql2 to connect using Hyperdrive, leaving the [ssl option](https://sidorares.github.io/node-mysql2/docs/documentation/ssl) undefined in the driver itself. (Hyperdrive is a connection pooler that also does query caching, which we're going to be making it available on the free plan for this)

2025-03-06 01:58 UTC, wellwelwel commented
> What we're thinking here is to make it possible to set ssl certs in a [Hyperdrive](https://developers.cloudflare.com/hyperdrive/get-started/) configuration rather than in the code itself. [Bindings](https://developers.cloudflare.com/workers/runtime-apis/bindings/), such as the Hyperdrive binding or the [mTLS binding](https://developers.cloudflare.com/workers/runtime-apis/bindings/mtls/), is usually how we resolve these limitations. Then we'd recommend folks use mysql2 to connect using Hyperdrive, leaving the [ssl option](https://sidorares.github.io/node-mysql2/docs/documentation/ssl) undefined in the driver itself. (Hyperdrive is a connection pooler that also does query caching, which we're going make available on the free plan for this)

@Mini256, I believe we can remove network wrapper and update the `"nodejs_compat"` flag usage in the examples:

```json
{
  "compatibility_flags": ["nodejs_compat"],
}
```

As **Hyperdrive** will be responsible for the secure TLS context with **Cloudflare Workers**, we can release the canary version with the documentation you have created. What do you think?

2025-03-06 02:00 UTC, Mini256 commented
@wellwelwel LGTM, let me rebase this PR and update the docs.

2025-03-06 03:34 UTC, Mini256 commented
@thomasgauvin According to the Hyperdrive documentation, it currently only supports the Postgres protocol, right? Are there any plan to support the MySQL and the MySQL protocol-compatible database (like TiDB Serverless, PlanetScale)

2025-03-06 04:42 UTC, wellwelwel requested changes

2025-03-06 04:42 UTC, wellwelwel commented on website/docs/documentation/connect-on-cloudflare.mdx
> +```
````suggestion
import { History } from '@site/src/components/History';

# Cloudflare Workers

<History
  records={[
    {
      version: '3.13.0',
      changes: [
        <>
          Support for <em>non-eval</em> parsers by using{' '}
          <strong>disableEval</strong> option.
        </>,
      ],
    },
  ]}
/>

## Prerequisites

- A [Cloudflare](https://dash.cloudflare.com/sign-up) account.
- [Wrangler](https://developers.cloudflare.com/workers/wrangler/) installed.
- **MySQL2** version `3.13.0` or higher.

To learn how to create a **Cloudflare Worker** project, please refer to [**Cloudflare Workers Documentation**](https://developers.cloudflare.com/workers/get-started/guide/).

## Setup

### Wrangler

**MySQL2** relies on **Node.js** modules, such as `net`, `events`, `stream`, `tls`, etc. You can enable **Node.js** compatibility for **Cloudflare Workers** by using the `"nodejs_compat"` flag through the `wrangler.jsonc` file:

```json
{
  "compatibility_flags": ["nodejs_compat"]
}
```

:::important
The minimum compatibility date is `2025-02-24`, for example:

```json
{
  "compatibility_date": "2025-02-24",
  "compatibility_flags": ["nodejs_compat"]
}
```

:::

### MySQL2 connection

**MySQL2** uses a code generation-based parser for performance by default, but since **Cloudflare Workers** don't offer support for evaluations, you can disable it by using the `disableEval` option:

```ts
import { createConnection } from 'mysql2/promise';

export default {
  async fetch(): Promise<Response> {
    const conn = await createConnection({
      host: 'localhost',
      user: 'root',
      database: 'test',
      // highlight-start
      disableEval: true,
      // highlight-end
    });

    const [results] = await conn.query('SHOW TABLES;');

    return new Response(JSON.stringify(results));
  },
} satisfies ExportedHandler<Env>;
```

:::tip
For required **SSL** connections, it is recommended to use the [**Cloudflare Hyperdrive**](https://developers.cloudflare.com/hyperdrive/) connection pool.
:::
````

2025-03-06 04:42 UTC, wellwelwel commented on website/docs/documentation/connect-on-cloudflare.mdx
> +```
I've slightly polished the texts and included a feature history. However, I've preferred to keep the details of how to use **Cloudflare Workers** to its own documentation in order to make this **MySQL2** section timeless.

I've also changed the **Cloudflare** login page to the sign-up page, as the official documentation suggests.

2025-03-06 05:11 UTC, merged

2025-03-06 05:28 UTC, wellwelwel commented
Thanks to everyone for your patience and great teamwork. Version `3.13.0` is out now.

2025-03-06 18:10 UTC, thomasgauvin commented
> @thomasgauvin According to the Hyperdrive documentation, it currently only supports the Postgres protocol, right? Are there any plan to support the MySQL and the MySQL protocol-compatible database (like TiDB Serverless, PlanetScale)

@Mini256, yes, getting the runtime to work with MySQL drivers goes hand in hand with our work to support MySQL on Hyperdrive. We're still working on it but I should be able to get any of you early access if you email me (first initial last name at cloudflare.com) or drop a chat in our [Discord channel](https://discord.com/invite/cloudflaredev)

2025-03-28 22:05 UTC, thomasgauvin commented
@wellwelwel how could we run tests to measure the performance difference between eval and static parsers?