Updated connection cleanup process to handle expired connections and those exceeding `config.maxIdle`
sidorares/node-mysql2 pull request #3022
Opened 2024-09-07 13:35 UTC by robert-pitt-foodhub

## Description

This PR addresses issue [#3020](https://github.com/sidorares/node-mysql2/issues/3020) by improving the connection cleanup process in the MySQL pool. The changes ensure that both connections exceeding the `config.maxIdle` setting and expired idle connections (those exceeding the `config.idleTimeout`) are correctly cleaned up.

### Summary of changes:

- **lib/pool.js**
  - Updated the connection cleanup logic to check for both `config.maxIdle` and expired connections based on `config.idleTimeout`.
  - Minor code cleanup for consistent formatting and code readability.
  
- **New tests:**
  - Added a new test `test-pool-release-idle-connection-timeout.test.cjs` to verify the removal of idle connections after the timeout period.
  - Adjusted `test-pool-release-idle-connection.test.cjs` to reflect the new cleanup behaviour.

### Key Changes:

- Improved connection cleanup mechanism in `lib/pool.js`.
- Added a new integration test to validate timeout-based cleanup (`test-pool-release-idle-connection-timeout.test.cjs`).
- Modified existing tests to cover new logic and ensure all scenarios are handled.

## Checklist

- [x] Code compiles correctly
- [x] All tests passing
- [ ] Relevant documentation updated (if applicable)
- [x] Verified with different pool configurations (e.g., low/high `idleTimeout`, `maxIdle`)

## How to Test

1. Create a pool with the following settings:
   - `connectionLimit: 3`
   - `maxIdle: 1`
   - `idleTimeout: 5000` (5 seconds)
   
2. Open and release 3 connections.
3. Ensure connections are removed after 5 seconds if idle.
4. Run the provided integration tests (`npm test` or equivalent).

## Linked Issues

- [Issue #3020](https://github.com/sidorares/node-mysql2/issues/3020)

## Screenshots (if applicable)

See linked issue

2024-09-07 17:08 UTC, wellwelwel commented
Thanks for the _PR_ and the detailed reports and explanations, @robert-pitt-foodhub 🤝

2024-09-07 18:47 UTC, robert-pitt-foodhub commented
Thanks @wellwelwel, Happy to help get this bug resolved, I have made another commit to the PR to add a new test case that specifically validates the connections are removed after. they are expired, let me know if there is any other test cases you would like me to address or documentation that needs updating.

Thanks

2024-09-09 11:49 UTC, wellwelwel commented
> also replying https://github.com/sidorares/node-mysql2/issues/3020#issuecomment-2337609504
@robert-pitt-foodhub, although the changes to the code are relatively simple, this seems a complex behavior to reproduce in a test case.

I tried removing your changes, keeping your test, but it didn't fail even with the current logic.

2024-09-10 00:20 UTC, robert-pitt-foodhub commented
Hey @wellwelwel, here's a failing test case that fail on the main branch but pass with the new code, Let me know if this helps

```
'use strict';

const createPool = require('../common.test.cjs').createPool;
const { assert } = require('poku');

const pool = new createPool({
  connectionLimit: 3,
  maxIdle: 2,
  idleTimeout: 1000,
});

/**
 * Create UP TO 3 connections, and allow a maximum of 2 idle connections, after
 * the 1000ms idle timeout has passed, within 1000ms of the timeout, all
 * connections should be closed if they are not in use.
 */

pool.getConnection((err1, connection1) => {
  assert.ifError(err1);
  assert.ok(connection1);
  // connection1.release();

  pool.getConnection((err2, connection2) => {
    assert.ifError(err2);
    assert.ok(connection2);
    // connection2.release();

    pool.getConnection((err3, connection3) => {
      assert.ifError(err3);
      assert.ok(connection3);
      // connection3.release();

      connection1.release();
      connection2.release();
      connection3.release();

      setTimeout(() => {
        assert(
          pool._allConnections.length === 0,
          `Expected all connections to be closed, but found ${pool._allConnections.length}`,
        );
        assert(
          pool._freeConnections.length === 0,
          `Expected all free connections to be closed, but found ${pool._freeConnections.length}`,
        );
      }, 5000);
    });
  });
});
```

2024-09-10 02:49 UTC, wellwelwel commented
Thanks @robert-pitt-foodhub, I believe this last test is ideal 🙋🏻‍♂️

2024-09-10 08:15 UTC, robert-pitt-foodhub commented
Would you like to to add this test to the PR test cases @wellwelwel

2024-09-10 08:19 UTC, wellwelwel commented
> Would you like to to add this test to the PR test cases @wellwelwel

For fixes, it's usually helpful to have a test that expects a failure to ensure that a new change doesn't break again in the future 🙋🏻‍♂️

2024-09-10 09:15 UTC, wellwelwel requested changes
The pool isn't being closed 🙋🏻‍♂️

2024-09-10 09:31 UTC, wellwelwel approved these changes

2024-09-10 09:37 UTC, wellwelwel commented
LGMT

Thanks again, @robert-pitt-foodhub 🤝
Can I merge or do you want to make some changes?

2024-09-10 09:39 UTC, robert-pitt-foodhub commented
Im happy for to you merge this yes, there is one other outstanding change which I think needs to be addressed which I noted in the Issue, but that we can deal with separately if you like.

Thanks for your support as well, go ahead and merge when your ready

2024-09-10 09:49 UTC, merged