fix(types): correct TypeCast's Next callback to return unknown
sidorares/node-mysql2 pull request #3129
Opened 2024-10-17 19:17 UTC by bbugh

Fixes "typeCast Next type appears to be incorrect" #3122

Also replaced references to the old incorrect type signature in referencing comments

2024-10-18 17:36 UTC, wellwelwel requested changes
Thanks, @bbugh.

I've suggested some rollback changes to the website's test files 🤝

2024-10-18 17:36 UTC, wellwelwel commented on website/test/fixtures/external-code-embed/QueryOptions.txt
> +   * You can also specify a function (field: any, next: () => unknown) => {} to do the type casting yourself.
There is no need to change the test fixtures or resources in `./website`. They just ensure string extractions in the `ExternalCodeEmbed` tests and are for internal use only 🙋🏻‍♂️

2024-10-18 17:36 UTC, wellwelwel commented on website/test/resources/external-code-embed/random-methods.txt
> +   * You can also specify a function (field: any, next: () => unknown) => {} to do the type casting yourself.
Same as above.

2024-10-31 17:11 UTC, bbugh commented
@wellwelwel I reverted the fixture files, it appears to be passing the checks now. Sorry for the trouble!

2024-10-31 17:22 UTC, wellwelwel approved these changes

2024-10-31 17:28 UTC, wellwelwel commented
Thanks again, @bbugh 🙋🏻‍♂️

2024-10-31 17:29 UTC, merged